name: "Running Jest tests"

env:
  PORT: ${{ secrets.PORT }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  SSL_KEY: ${{ secrets.SSL_KEY }}
  SSL_CERT: ${{ secrets.SSL_CERT }}
  SSL_KEY_PASSWORD: ${{ secrets.SSL_CA }}
  SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

on:
  push:
    branches:
      - "main"
      - "production"
  pull_request:
    branches:
      - "main"
      - "production"
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./beschlusswiki-backend # Hier das gewünschte Arbeitsverzeichnis angeben

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build # Ersetze dies durch deinen tatsächlichen Build-Befehl, z. B. "tsc" für TypeScript

      - name: Run Jest Tests
        run: npm test
